use axum::{
    routing::{get, post},
    Router,
    response::IntoResponse,
    http::{header, StatusCode, Uri},
    extract::DefaultBodyLimit,
};
use tower_http::trace::TraceLayer;
use std::net::SocketAddr;
use std::sync::Arc;
use rust_embed::RustEmbed;
use oauth2::{
    AuthUrl, ClientId, ClientSecret, RedirectUrl, TokenUrl,
    basic::BasicClient,
};

mod github;
mod routes;
mod templates;

// Asset version from build time
// Asset version from build time (generated by build.rs)
pub const ASSET_VERSION: &str = env!("ASSET_VERSION");

#[derive(RustEmbed)]
#[folder = "assets"]
struct Assets;

async fn static_handler(uri: Uri) -> impl IntoResponse {
    let path = uri.path().trim_start_matches('/');
    let path = path.strip_prefix("assets/").unwrap_or(path);
    
    println!("Requesting static file: '{}' (original: '{}')", path, uri.path());

    match Assets::get(path) {
        Some(content) => {
            let mime = mime_guess::from_path(path).first_or_octet_stream();
            println!("Found file: '{}', mime: '{}'", path, mime.as_ref());
            
            // Add cache control headers
            // Cache for 1 year if versioned (has ?v= param), otherwise no-cache
            let cache_header = if uri.query().and_then(|q| q.strip_prefix("v=")).is_some() {
                "public, max-age=31536000, immutable"
            } else {
                "no-cache, must-revalidate"
            };
            
            ([
                (header::CONTENT_TYPE, mime.as_ref()),
                (header::CACHE_CONTROL, cache_header),
            ], content.data).into_response()
        }
        None => {
            println!("File NOT found: '{}'", path);
            // List available files for debugging
            for file in Assets::iter() {
                println!("Available asset: {}", file.as_ref());
            }
            StatusCode::NOT_FOUND.into_response()
        }
    }
}

#[tokio::main]
async fn main() {
    // Load .env file if present (for local development and deployment)
    dotenv::dotenv().ok();
    
    // Initialize tracing
    tracing_subscriber::fmt::init();

    println!("Asset version (build time): {}", ASSET_VERSION);

    // Setup OAuth client (optional - will work without credentials but OAuth login disabled)
    let oauth_client = std::env::var("GITHUB_CLIENT_ID")
        .ok()
        .zip(std::env::var("GITHUB_CLIENT_SECRET").ok())
        .map(|(client_id, client_secret)| {
            let auth_url = AuthUrl::new("https://github.com/login/oauth/authorize".to_string())
                .expect("Invalid authorization endpoint URL");
            let token_url = TokenUrl::new("https://github.com/login/oauth/access_token".to_string())
                .expect("Invalid token endpoint URL");

            // Use environment variable for callback URL, fallback to localhost
            let callback_url = std::env::var("OAUTH_CALLBACK_URL")
                .unwrap_or_else(|_| "http://localhost:3002/auth/callback".to_string());
            
            let redirect_url = RedirectUrl::new(callback_url)
                .expect("Invalid redirect URL");

            BasicClient::new(
                ClientId::new(client_id),
                Some(ClientSecret::new(client_secret)),
                auth_url,
                Some(token_url),
            )
            .set_redirect_uri(redirect_url)
        });

    if oauth_client.is_some() {
        println!("GitHub OAuth is enabled");
    } else {
        println!("GitHub OAuth is disabled (set GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET to enable)");
    }

    let app = Router::new()
        .route("/", get(routes::index))
        .route("/login", post(routes::login))
        .route("/auth/github", get(routes::auth_github))
        .route("/auth/callback", get(routes::auth_callback))
        .route("/logout", get(routes::logout))
        .route("/dashboard", get(routes::dashboard))
        .route("/upload", post(routes::upload))
        .route("/delete", post(routes::delete_image))
        .route("/assets/*file", get(static_handler))
        .layer(DefaultBodyLimit::max(50 * 1024 * 1024)) // 50MB limit
        .layer(TraceLayer::new_for_http())
        .with_state(Arc::new(oauth_client));

    let addr = SocketAddr::from(([127, 0, 0, 1], 3002));
    println!("Listening on http://{}", addr);
    
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
